import {readFile,writeFile,rename,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createCipheriv,createDecipheriv,randomBytes,createHash} from 'node:crypto';
const root=()=>resolve(process.env.MAD_DATA_DIR||'.');
const vault=()=>join(root(),'netapoz-credentials.enc');
function key(){const value=process.env.MAD_CREDENTIALS_KEY;if(!/^[a-f0-9]{64}$/i.test(value||''))throw Error('Credential storage unavailable');return Buffer.from(value,'hex')}
async function atomic(path,content){await mkdir(root(),{recursive:true,mode:0o700});const temp=path+'.'+randomBytes(8).toString('hex');await writeFile(temp,content,{mode:0o600,flag:'wx'});await rename(temp,path)}
export async function configured(){try{await readFile(vault());return true}catch(e){if(e.code==='ENOENT')return false;throw e}}
export async function saveCredentials(data){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);cipher.setAAD(Buffer.from('MAD Netapoz v1'));const encrypted=Buffer.concat([cipher.update(JSON.stringify(data),'utf8'),cipher.final()]);await atomic(vault(),JSON.stringify({iv:iv.toString('hex'),tag:cipher.getAuthTag().toString('hex'),data:encrypted.toString('hex')}))}
async function credentials(){const raw=await readFile(vault(),'utf8');const encrypted=JSON.parse(raw),decipher=createDecipheriv('aes-256-gcm',key(),Buffer.from(encrypted.iv,'hex'));decipher.setAAD(Buffer.from('MAD Netapoz v1'));decipher.setAuthTag(Buffer.from(encrypted.tag,'hex'));return {version:createHash('sha256').update(raw).digest('hex'),data:JSON.parse(Buffer.concat([decipher.update(Buffer.from(encrypted.data,'hex')),decipher.final()]).toString('utf8'))}}
export async function loginVendor(data,fetcher=fetch){const url=new URL('https://www.netapoz.com/auth/password/management');url.searchParams.set('accountName',data.accountName);const r=await fetcher(url,{headers:{Authorization:'Basic '+Buffer.from(data.username+':'+data.password).toString('base64')},redirect:'error',signal:AbortSignal.timeout(30000)});if(!r.ok){const e=new Error('Netapoz authentication failed');e.status=r.status;throw e}const cookie=r.headers.getSetCookie().map(s=>s.split(';')[0]).find(s=>/^SESSION=[^\s;]+$/.test(s));if(!cookie)throw Error('Netapoz did not return a session');return cookie}
export async function saveSession(cookie){await atomic(join(root(),'.env.netapoz-session'),JSON.stringify({cookie}))}
export async function renewSession(fetcher=fetch){const current=await credentials();let blocked={};try{blocked=JSON.parse(await readFile(join(root(),'netapoz-auth-block.json'),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e}if(blocked.version===current.version)throw Error('Credentials rejected; update required');try{const cookie=await loginVendor(current.data,fetcher);await saveSession(cookie);return cookie}catch(e){if([401,403].includes(e.status))await atomic(join(root(),'netapoz-auth-block.json'),JSON.stringify({version:current.version}));throw e}}
