'use client';
import {useState} from 'react';
import {Video,Download} from 'lucide-react';
import {Sale,statusText} from '@/lib/branches';
import {saleDay} from '@/lib/sale-day';
import {Button} from '@/components/ui/button';
import {summarizeSales,csvSummary} from '@/lib/sales-summary';
const money=(n:number,c='ILS')=>new Intl.NumberFormat('ar',{style:'currency',currency:c}).format(n/100);
const invoice=(id:string)=>{try{return JSON.parse(id)[2]}catch{return id}};
export default function DailySales({sales,branches,day,onDay,filter,onFilter,onSelect,loading}:{sales:Sale[];branches:{id:string;name:string}[];day:string;onDay:(v:string)=>void;filter:string;onFilter:(v:string)=>void;onSelect:(v:Sale)=>void;loading:boolean}){
 const [employee,setEmployee]=useState('all');
 const branchRows=sales.filter(s=>filter==='all'||s.branchId===filter);
 const employees=Array.from(new Set(branchRows.map(s=>s.cashier).filter(Boolean))).sort();
 const selectedEmployee=employees.includes(employee)?employee:'all';
 const rows=branchRows.filter(s=>selectedEmployee==='all'||s.cashier===selectedEmployee);
 const summary=summarizeSales(rows,branches.filter(b=>filter==='all'||b.id===filter));
 function changeDay(v:string){if(v){setEmployee('all');onDay(v)}}
 function step(n:number){changeDay(new Date(Date.parse(day+'T12:00:00Z')+n*86400000).toISOString().slice(0,10))}
 function download(){const blob=new Blob(['\uFEFF'+csvSummary(summary,day)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='MAD-sales-'+day+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <><section className="panel"><div className="panel-head"><h2>عمليات اليوم المختار</h2><span>{rows.length} عملية</span></div><div className="sales-filters"><label>التاريخ<input aria-label="تاريخ العمليات" type="date" value={day} onChange={e=>changeDay(e.target.value)}/></label><div className="day-actions"><Button variant="outline" onClick={()=>step(-1)}>اليوم السابق</Button><Button variant="outline" onClick={()=>changeDay(saleDay())}>اليوم</Button><Button variant="outline" disabled={day>=saleDay()} onClick={()=>step(1)}>اليوم التالي</Button></div><label>الفرع<select aria-label="تصفية حسب الفرع" value={filter} onChange={e=>{onFilter(e.target.value);setEmployee('all')}}><option value="all">جميع الفروع</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>الموظف / الكاشير<select aria-label="تصفية حسب الموظف" value={selectedEmployee} onChange={e=>setEmployee(e.target.value)}><option value="all">جميع الموظفين</option>{employees.map(n=><option key={n}>{n}</option>)}</select></label></div><p className="filter-note">بتوقيت القدس · الموظف حسب الاسم الوارد في الفاتورة · الملخص يتبع الاختيارات أعلاه.</p></section>
 <section className="panel daily-summary"><div className="panel-head"><div><h2>ملخص المبيعات لكل فرع</h2><p className="sub">{day} · المبيعات المستوردة من Netapoz</p></div><Button variant="outline" onClick={download} disabled={loading}><Download size={16}/> تنزيل الملخص</Button></div><div className="summary-grid">{summary.map(b=><article key={b.branchId+b.currency}><strong>{b.name}</strong><b className="summary-total">{money(b.total,b.currency)}</b><span>{b.count} فاتورة</span><dl><div><dt>نقدي</dt><dd>{money(b.cash,b.currency)}</dd></div><div><dt>بطاقات</dt><dd>{money(b.card,b.currency)}</dd></div>{b.other!==0&&<div><dt>مختلط / طرق أخرى</dt><dd>{money(b.other,b.currency)}</dd></div>}</dl></article>)}</div></section>
 <section className="panel"><div className="panel-head"><h2>الفواتير والتسجيلات</h2></div><div className="sales-desktop"><table className="daily-table"><thead><tr>{['الفرع / الفاتورة','الموظف','الوقت','المبلغ','الدفع','الفيديو'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><strong>{branches.find(b=>b.id===s.branchId)?.name||s.branchId}</strong><small>{invoice(s.id)}</small></td><td>{s.cashier}</td><td>{new Date(s.occurredAt).toLocaleTimeString('ar',{timeZone:'Asia/Jerusalem',hour:'2-digit',minute:'2-digit'})}</td><td>{money(s.amountMinor,s.currency)}</td><td>{s.payment}</td><td><Button variant="ghost" onClick={()=>onSelect(s)}><Video size={16}/>{statusText[s.status]||s.status}</Button></td></tr>)}</tbody></table></div><div className="sales-mobile">{rows.map(s=><article className="sale-card" key={s.id}><div className="sale-card-head"><strong>{branches.find(b=>b.id===s.branchId)?.name||s.branchId}</strong><b>{money(s.amountMinor,s.currency)}</b></div><dl><div><dt>الفاتورة</dt><dd>{invoice(s.id)}</dd></div><div><dt>الموظف</dt><dd>{s.cashier||'غير مذكور'}</dd></div><div><dt>الوقت</dt><dd>{new Date(s.occurredAt).toLocaleTimeString('ar',{timeZone:'Asia/Jerusalem',hour:'2-digit',minute:'2-digit'})}</dd></div><div><dt>الدفع</dt><dd>{s.payment}</dd></div></dl><Button className="sale-video-button" variant={s.status==='ready'?'default':'outline'} onClick={()=>onSelect(s)}><Video size={18}/>{s.status==='ready'?'مشاهدة الفيديو والتفاصيل':'تفاصيل العملية · '+(statusText[s.status]||s.status)}</Button></article>)}</div>{!rows.length&&<div className="daily-empty">{loading?'جارٍ تحميل العمليات…':'لا توجد عمليات مطابقة في هذا اليوم. اختر تاريخًا أو تصفية أخرى.'}</div>}<div className="panel-foot">المقاطع محفوظة حسب المساحة المتاحة؛ يُحذف الأقدم عند امتلائها.</div></section></>
}
