 'use client';
import {useEffect,useState} from 'react';
type Row=Record<string,string|number|boolean>;
type Data={actor:{id:string;role:string};branches:Row[];registers:Row[];devices:Row[];members:Row[];mappings:Row[];audit:Row[]};
export default function Manage(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[kind,setKind]=useState('branch'),[form,setForm]=useState<Row>({id:'',name:'',active:true,channels:4,role:'viewer'}),[busy,setBusy]=useState(false);
async function load(){const r=await fetch('/api/manage');if(r.status===401){location.assign('/login');return}if(!r.ok)throw Error('تعذّر تحميل الإدارة');setData(await r.json())}useEffect(()=>{load().catch(e=>setError(e.message))},[]);
async function save(payload:Row){setBusy(true);setError('');try{const r=await fetch('/api/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);await load();setForm({...form,password:''});setError('تم الحفظ')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function choose(k:string,row?:Row){setKind(k);setForm(row?{...row,active:!!row.active,branchId:row.branch_id||row.branchId||'',password:''}:{id:'',name:'',active:true,channels:4,role:'viewer',branchId:'',registerId:'',device:'',channel:1,offsetSeconds:0})}
function field(key:string,label:string,type='text'){return <label>{label}<input required={key!=='password'} type={type} value={String(form[key]??'')} onChange={e=>setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>}
const editable=data&&data.actor.role!=='viewer';const names:Record<string,string>={branch:'الفروع',register:'الكاشيرات',device:'أجهزة التسجيل',mapping:'ربط الكاميرات',member:'المستخدمون'};
return <main dir="rtl" style={{maxWidth:1100,margin:'30px auto',padding:24}}><a href="/">العودة للمتابعات</a><h1>إدارة النظام</h1><a href="/integrations">إعداد الاتصال الدائم بـNetapoz</a><p>تعطيل السجل يوقف تجهيز المقاطع المرتبطة به ويحافظ على الفواتير السابقة. صلاحية المشاهدة للقراءة فقط؛ المشغّل يدير الربط؛ المدير يدير المستخدمين أيضًا.</p><style>{`input,select{display:block;padding:10px;border:1px solid #bbb;border-radius:6px;width:100%;margin:6px 0}button{padding:8px 14px;margin:4px;border:1px solid #bbb;border-radius:6px}table{width:100%;border-collapse:collapse;margin:20px 0}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:right}label{display:block}form{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px;background:#f5f5f0;padding:18px}input[type=checkbox]{width:auto}`}</style>
{error&&<p role="status">{error}</p>}{data&&<><nav>{Object.entries(names).filter(([k])=>k!=='member'||data.actor.role==='admin').map(([k,n])=><button key={k} onClick={()=>choose(k)}>{n}</button>)}</nav><h2>{names[kind]}</h2>{editable&&<form onSubmit={e=>{e.preventDefault();const payload:Row={entity:kind,...form};if(!payload.password)delete payload.password;save(payload)}}>
{kind!=='mapping'&&<>{field('id','المعرّف الثابت')}{field('name',kind==='register'?'اسم الكاشير كما يظهر في Netapoz':'الاسم')}<label>مفعّل<input type="checkbox" checked={!!form.active} onChange={e=>setForm({...form,active:e.target.checked})}/></label></>}
{(kind==='register'||kind==='mapping')&&<label>الفرع<select required value={String(form.branchId||'')} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">اختر الفرع</option>{data.branches.map(b=><option key={String(b.id)} value={String(b.id)}>{b.name}</option>)}</select></label>}
{kind==='device'&&<>{field('channels','عدد القنوات','number')}<p>يجب أن يطابق المعرّف اسم الجهاز في وسيط Dahua على Mac. إضافة السجل هنا لا تنشئ اتصالًا أو تنقل كلمة مرور الجهاز.</p></>}
{kind==='mapping'&&<><label>الكاشير<select required value={String(form.registerId||'')} onChange={e=>setForm({...form,registerId:e.target.value})}><option value="">اختر الكاشير</option>{data.registers.filter(r=>r.branch_id===form.branchId).map(r=><option key={String(r.id)}>{r.name}</option>)}</select></label><label>الجهاز<select required value={String(form.device||'')} onChange={e=>setForm({...form,device:e.target.value})}><option value="">اختر الجهاز</option>{data.devices.map(d=><option key={String(d.id)} value={String(d.id)}>{d.name}</option>)}</select></label>{field('channel','القناة','number')}{field('offsetSeconds','تصحيح الوقت بالثواني','number')}</>}
{kind==='member'&&<><label>الصلاحية<select value={String(form.role)} onChange={e=>setForm({...form,role:e.target.value})}><option value="viewer">مشاهدة</option><option value="operator">تشغيل</option><option value="admin">إدارة</option></select></label>{field('password','كلمة مرور جديدة (12 حرفًا على الأقل؛ اتركها فارغة للإبقاء على الحالية)','password')}</>}
<button disabled={busy}>حفظ</button></form>}
<table><thead><tr><th>السجل</th><th>التفاصيل</th><th>الإجراءات</th></tr></thead><tbody>{(kind==='branch'?data.branches:kind==='register'?data.registers:kind==='device'?data.devices:kind==='member'?data.members:data.mappings).map((r,i)=><tr key={i}><td>{String(r.name||r.registerId)}<small style={{display:'block'}}>{String(r.id||r.branchId)}</small></td><td>{kind==='mapping'?`${r.device} / ${r.channel}`:kind==='device'?`${r.channels} قنوات — ${r.active?'مفعّل':'معطّل'}`:kind==='member'?String(r.role):r.active?'مفعّل':'معطّل'}</td><td>{editable&&<><button onClick={()=>choose(kind,r)}>تعديل</button>{kind==='mapping'&&<button disabled={busy} onClick={()=>save({entity:'mapping',...r,remove:true})}>فصل الربط</button>}</>}</td></tr>)}</tbody></table>
{data.actor.role==='admin'&&<><h2>سجل التغييرات</h2><table><thead><tr><th>الوقت</th><th>المستخدم</th><th>الإجراء</th><th>السجل</th></tr></thead><tbody>{data.audit.map(r=><tr key={String(r.id)}><td>{new Date(Number(r.created_at)).toLocaleString('ar')}</td><td>{r.actor}</td><td>{r.action} / {r.entity}</td><td>{r.entity_id}</td></tr>)}</tbody></table></>}</>}
</main>}
