import {actor} from '@/lib/auth';
import {sameOrigin,json} from '@/lib/server';
import {sqlite} from '@/lib/node-storage';
import {catalog,audit,transaction,passwordHash,saveMapping,eligibleSQL} from '@/lib/management';
import {z} from 'zod';
const id=z.string().trim().regex(/^[A-Za-z0-9_-]{1,80}$/);
const name=z.string().trim().min(1).max(120);
const schema=z.discriminatedUnion('entity',[
 z.object({entity:z.literal('branch'),id,name,active:z.boolean()}),
 z.object({entity:z.literal('register'),id,branchId:id,name,active:z.boolean()}),
 z.object({entity:z.literal('device'),id,name,channels:z.number().int().min(1).max(8),active:z.boolean()}),
 z.object({entity:z.literal('member'),id,name,role:z.enum(['admin','operator','viewer']),active:z.boolean(),password:z.string().min(12).max(256).optional()}),
 z.object({entity:z.literal('mapping'),branchId:id,registerId:name,device:id,channel:z.number().int().min(1).max(8),offsetSeconds:z.number().int().min(-86400).max(86400),remove:z.boolean().optional()}),
 z.object({entity:z.literal('retry'),id:z.string().min(1).max(500)})
]);
export async function GET(){const a=await actor();if(!a)return json({error:'Unauthorized'},401);const c=sqlite();return json({...catalog(),actor:a,mappings:c.prepare('SELECT branch_id AS branchId,register_id AS registerId,device,channel,offset_seconds AS offsetSeconds FROM mappings').all(),members:a.role==='admin'?c.prepare('SELECT id,name,role,active FROM members ORDER BY name').all():[],audit:a.role==='admin'?c.prepare('SELECT * FROM audit ORDER BY created_at DESC LIMIT 100').all():[]});}
export async function POST(r:Request){const a=await actor();if(!a)return json({error:'Unauthorized'},401);if(a.role==='viewer'||!sameOrigin(r))return json({error:'Forbidden'},403);try{const text=await r.text();if(text.length>8192)return json({error:'Too large'},413);const d=schema.parse(JSON.parse(text));if(d.entity==='member'&&a.role!=='admin')return json({error:'Forbidden'},403);transaction(()=>{const c=sqlite();switch(d.entity){
case 'branch':c.prepare('INSERT INTO branches VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active').run(d.id,d.name,Number(d.active));break;
case 'device':if(c.prepare('SELECT 1 FROM mappings WHERE device=? AND channel>?').get(d.id,d.channels))throw Error('توجد قناة مرتبطة تتجاوز عدد القنوات الجديد');c.prepare('INSERT INTO devices VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,channels=excluded.channels,active=excluded.active').run(d.id,d.name,d.channels,Number(d.active));break;
case 'register':if(!c.prepare('SELECT 1 FROM branches WHERE id=? AND active=1').get(d.branchId))throw Error('الفرع غير مفعّل');const old=c.prepare('SELECT * FROM registers WHERE id=?').get(d.id);if(old&&(old.branch_id!==d.branchId||old.name!==d.name)&&c.prepare('SELECT 1 FROM mappings WHERE branch_id=? AND register_id=?').get(String(old.branch_id),String(old.name)))throw Error('افصل ربط الكاميرا قبل تغيير الفرع أو اسم الكاشير');c.prepare('INSERT INTO registers VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET branch_id=excluded.branch_id,name=excluded.name,active=excluded.active').run(d.id,d.branchId,d.name,Number(d.active));break;
case 'member':if(d.id==='owner'||d.id===a.id)throw Error('لا يمكن تغيير الحساب الحالي من هذه الشاشة');const existing=c.prepare('SELECT password_hash FROM members WHERE id=?').get(d.id);if(!existing&&!d.password)throw Error('كلمة مرور مطلوبة للمستخدم الجديد');c.prepare('INSERT INTO members VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,role=excluded.role,password_hash=excluded.password_hash,active=excluded.active').run(d.id,d.name,d.role,d.password?passwordHash(d.password):String(existing!.password_hash),Number(d.active));c.prepare('DELETE FROM app_sessions WHERE member_id=?').run(d.id);break;
case 'mapping':if(d.remove){c.prepare('DELETE FROM mappings WHERE branch_id=? AND register_id=?').run(d.branchId,d.registerId);c.prepare("UPDATE sales SET status='unmapped',lease=NULL,lease_until=NULL WHERE branch_id=? AND register_id=? AND status IN ('queued','processing')").run(d.branchId,d.registerId);audit(a,'remove','mapping',JSON.stringify([d.branchId,d.registerId]));}else saveMapping(a,d);return;
case 'retry':const result=c.prepare("UPDATE sales SET status='queued',attempts=0,next_attempt=?,error=NULL WHERE id=? AND status='failed' AND occurred_at>? AND EXISTS(SELECT 1 FROM mappings WHERE branch_id=sales.branch_id AND register_id=sales.register_id)").run(Date.now(),d.id,Date.now()-30*86400000);if(!result.changes)throw Error('العملية غير قابلة لإعادة المحاولة');break;
}if(['branch','register','device'].includes(d.entity)){c.prepare(`UPDATE sales SET status='unmapped',lease=NULL,lease_until=NULL WHERE status IN ('queued','processing') AND NOT EXISTS(SELECT 1 FROM (${eligibleSQL}) m WHERE m.branch_id=sales.branch_id AND m.register_id=sales.register_id)`).run();c.prepare(`UPDATE sales SET status='queued' WHERE status='unmapped' AND EXISTS(SELECT 1 FROM (${eligibleSQL}) m WHERE m.branch_id=sales.branch_id AND m.register_id=sales.register_id)`).run();}audit(a,'save',d.entity,d.id,d.entity==='member'?{name:d.name,role:d.role,active:d.active,passwordChanged:!!d.password}:d);});return json({ok:true});}catch(e){return json({error:e instanceof z.ZodError?'تحقق من الحقول المطلوبة':e instanceof Error&&!e.message.includes('SQLITE')&&!e.message.includes('constraint')?e.message:'تعذّر الحفظ؛ تحقق من وجود سجل بنفس البيانات'},400);}}
