import {cookies} from 'next/headers';
import {createHash,scryptSync,timingSafeEqual,randomBytes} from 'node:crypto';
import {sqlite} from './node-storage';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export async function actor():Promise<{id:string;role:'admin'|'operator'|'viewer'}|null>{const value=(await cookies()).get('__Host-mad_session')?.value;if(!value)return null;const session=sqlite().prepare('SELECT member_id FROM app_sessions WHERE token_hash=? AND expires_at>?').get(hash(value),Date.now());if(!session)return null;if(session.member_id==='owner')return {id:'owner',role:'admin'};const member=sqlite().prepare('SELECT id,role FROM members WHERE id=? AND active=1').get(String(session.member_id));return member?member as {id:string;role:'admin'|'operator'|'viewer'}:null;}
export async function viewer(){return !!await actor();}
export function checkPassword(password:string,username='owner'){const value=username==='owner'?process.env.MAD_ADMIN_PASSWORD_HASH:String(sqlite().prepare('SELECT password_hash FROM members WHERE id=? AND active=1').get(username)?.password_hash||'');if(!value)return false;const [salt,expected]=value.split(':');if(!salt||!expected)return false;const actual=scryptSync(password,salt,64),target=Buffer.from(expected,'hex');return target.length===actual.length&&timingSafeEqual(target,actual);}
export function createSession(memberId='owner'){const value=randomBytes(32).toString('base64url');sqlite().prepare('DELETE FROM app_sessions WHERE expires_at<=?').run(Date.now());sqlite().prepare('INSERT INTO app_sessions(token_hash,expires_at,member_id) VALUES(?,?,?)').run(hash(value),Date.now()+30*86400000,memberId);return value;}
export async function revokeSession(){const value=(await cookies()).get('__Host-mad_session')?.value;if(value)sqlite().prepare('DELETE FROM app_sessions WHERE token_hash=?').run(hash(value));}
export function allowLogin(){const now=Date.now();sqlite().prepare('DELETE FROM login_attempts WHERE at<?').run(now-600000);const row=sqlite().prepare('SELECT count(*) AS n FROM login_attempts').get();if(Number(row?.n)>=15)return false;sqlite().prepare('INSERT INTO login_attempts(at) VALUES(?)').run(now);return true;}
export function clearAttempts(){sqlite().exec('DELETE FROM login_attempts');}
