import {sqlite} from './node-storage';
import {randomUUID,scryptSync,randomBytes} from 'node:crypto';
export type Actor={id:string;role:'admin'|'operator'|'viewer'};
export function audit(actor:Actor,action:string,entity:string,id:string,details:unknown={}){sqlite().prepare('INSERT INTO audit VALUES(?,?,?,?,?,?,?)').run(randomUUID(),actor.id,action,entity,id,JSON.stringify(details),Date.now());}
export function passwordHash(password:string){const salt=randomBytes(24).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex');}
export function catalog(){const c=sqlite();return {branches:c.prepare('SELECT * FROM branches ORDER BY name').all(),registers:c.prepare('SELECT * FROM registers ORDER BY name').all(),devices:c.prepare('SELECT * FROM devices ORDER BY name').all()};}
export const eligibleSQL=`SELECT m.* FROM mappings m JOIN branches b ON b.id=m.branch_id JOIN registers r ON r.branch_id=m.branch_id AND r.name=m.register_id JOIN devices d ON d.id=m.device WHERE b.active=1 AND r.active=1 AND d.active=1 AND m.channel<=d.channels`;
export function saveMapping(actor:Actor,m:{branchId:string;registerId:string;device:string;channel:number;offsetSeconds:number}){const c=sqlite();const valid=c.prepare('SELECT 1 FROM branches b JOIN registers r ON r.branch_id=b.id JOIN devices d ON d.id=? WHERE b.id=? AND r.name=? AND b.active=1 AND r.active=1 AND d.active=1 AND d.channels>=?').get(m.device,m.branchId,m.registerId,m.channel);if(!valid)throw Error('اختر فرعًا وكاشيرًا وجهازًا مفعّلين وقناة ضمن عدد قنوات الجهاز');c.prepare('INSERT INTO mappings VALUES(?,?,?,?,?) ON CONFLICT(branch_id,register_id) DO UPDATE SET device=excluded.device,channel=excluded.channel,offset_seconds=excluded.offset_seconds').run(m.branchId,m.registerId,m.device,m.channel,m.offsetSeconds);c.prepare("UPDATE sales SET status='queued' WHERE branch_id=? AND register_id=? AND status='unmapped'").run(m.branchId,m.registerId);audit(actor,'save','mapping',JSON.stringify([m.branchId,m.registerId]),m);}
export function transaction<T>(fn:()=>T){const c=sqlite();c.exec('BEGIN IMMEDIATE');try{const value=fn();c.exec('COMMIT');return value}catch(e){c.exec('ROLLBACK');throw e}}
