FROM docker.io/library/ubuntu:24.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends wine64 ca-certificates && rm -rf /var/lib/apt/lists/*
ENV WINEDEBUG=-all WINEARCH=win64 WINEPREFIX=/wine
WORKDIR /sdk
ENTRYPOINT ["/usr/lib/wine/wine64"]
