import {RETENTION_DAYS,retentionCutoff} from '@/lib/retention';
import {db,viewer,sameOrigin,json,saleRow,runtime} from '@/lib/server';
import {catalog,saveMapping,transaction} from '@/lib/management';
import {actor} from '@/lib/auth';
import {z} from 'zod';
export const dynamic='force-dynamic';
export async function GET(){if(!await viewer())return json({error:'Unauthorized'},401);try{const serverTime=Date.now();const [s,m,integration,videoIntegration,retentionIntegration]=await Promise.all([db().prepare('SELECT * FROM sales ORDER BY occurred_at DESC LIMIT 200').all(),db().prepare('SELECT branch_id AS branchId,register_id AS registerId,device,channel,offset_seconds AS offsetSeconds FROM mappings').all(),db().prepare("SELECT status,last_success AS lastSuccess FROM integrations WHERE id='netapoz'").first(),db().prepare("SELECT status,last_success AS lastSuccess FROM integrations WHERE id='dahua'").first(),db().prepare("SELECT status,last_success AS lastSuccess FROM integrations WHERE id='retention'").first()]);return json({branches:catalog().branches,sales:s.results.map(row=>saleRow(Number(row.occurred_at)<=retentionCutoff(serverTime)&&row.status!=='expired'?{...row,status:row.clip_key?'expiring':'expired'}:row)),mappings:m.results,serverTime,integration,videoIntegration,retentionDays:RETENTION_DAYS,retentionIntegration,bridgeConfigured:!!runtime.MAD_BRIDGE_TOKEN});}catch{return json({error:'Storage unavailable'},503)}}
const schema=z.object({action:z.literal('mapping'),branchId:z.string().min(1).max(80),registerId:z.string().trim().min(1).max(100),device:z.string().trim().regex(/^[A-Za-z0-9_-]{1,64}$/),channel:z.number().int().min(1).max(8),offsetSeconds:z.number().int().min(-86400).max(86400)});
export async function POST(r:Request){const a=await actor();if(!a)return json({error:'Unauthorized'},401);if(a.role==='viewer'||!sameOrigin(r))return json({error:'Forbidden'},403);try{const m=schema.parse(await r.json());transaction(()=>saveMapping(a,m));return json({ok:true});}catch{return json({error:'تحقق من الفرع والكاشير والجهاز والقناة في الإدارة'},400)}}
