CREATE TABLE branches(id TEXT PRIMARY KEY,name TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE registers(id TEXT PRIMARY KEY,branch_id TEXT NOT NULL REFERENCES branches(id),name TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,UNIQUE(branch_id,name));
CREATE TABLE devices(id TEXT PRIMARY KEY,name TEXT NOT NULL,channels INTEGER NOT NULL DEFAULT 4 CHECK(channels BETWEEN 1 AND 8),active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE members(id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('admin','operator','viewer')),password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE audit(id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,entity TEXT NOT NULL,entity_id TEXT NOT NULL,details TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX idx_audit_created ON audit(created_at);
CREATE TABLE IF NOT EXISTS app_sessions(token_hash TEXT PRIMARY KEY,expires_at INTEGER NOT NULL);
ALTER TABLE app_sessions ADD COLUMN member_id TEXT NOT NULL DEFAULT 'owner';
INSERT OR IGNORE INTO branches(id,name) SELECT DISTINCT branch_id,branch_id FROM sales;
INSERT OR IGNORE INTO branches(id,name) SELECT DISTINCT branch_id,branch_id FROM mappings;
INSERT OR IGNORE INTO registers(id,branch_id,name) SELECT lower(hex(randomblob(16))),branch_id,register_id FROM sales;
INSERT OR IGNORE INTO registers(id,branch_id,name) SELECT lower(hex(randomblob(16))),branch_id,register_id FROM mappings;
INSERT OR IGNORE INTO devices(id,name,channels) SELECT device,device,max(4,max(channel)) FROM mappings GROUP BY device;
INSERT INTO branches(id,name) VALUES('25274','العفولة') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('29269','بئر السبع') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('25351','أم الفحم · وادي النسور') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('37615','الناصرة · الشارع الرئيسي') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('31165','الناصرة · توفيق زياد') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('16789','أم الفحم · المدينة') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('6386','يركا') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('9607','حيفا') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('24897','كفر قرع') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('23618','هرتسليا') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
INSERT INTO branches(id,name) VALUES('25066','الخضيرة') ON CONFLICT(id) DO UPDATE SET name=excluded.name;
